---
create_comments: false # no write operations will be performed, only debug output will be printed and the report will be generated
issue_stale_threshold_days: 180
comment_body: "This issue has been inactive for 180 days. Please consider updating it or closing if not relevant anymore."

paths:
  report_markdown_template: STALE_ISSUES_REPORT_TEMPLATE.md
  log_file: logs.json
  report_dir: reports
...